export interface UniverseEntry {
  ticker: string;
  name: string;
  sector: string;
}

export const STOCK_UNIVERSE: UniverseEntry[] = [
  // ── Information Technology ────────────────────────────────────────────────
  { ticker: "AAPL",  name: "Apple Inc.",                    sector: "Information Technology" },
  { ticker: "MSFT",  name: "Microsoft Corp.",               sector: "Information Technology" },
  { ticker: "NVDA",  name: "NVIDIA Corp.",                  sector: "Information Technology" },
  { ticker: "AVGO",  name: "Broadcom Inc.",                 sector: "Information Technology" },
  { ticker: "ORCL",  name: "Oracle Corp.",                  sector: "Information Technology" },
  { ticker: "CRM",   name: "Salesforce Inc.",               sector: "Information Technology" },
  { ticker: "AMD",   name: "Advanced Micro Devices",        sector: "Information Technology" },
  { ticker: "QCOM",  name: "Qualcomm Inc.",                 sector: "Information Technology" },
  { ticker: "ACN",   name: "Accenture plc",                 sector: "Information Technology" },
  { ticker: "CSCO",  name: "Cisco Systems",                 sector: "Information Technology" },
  { ticker: "IBM",   name: "IBM Corp.",                     sector: "Information Technology" },
  { ticker: "NOW",   name: "ServiceNow Inc.",               sector: "Information Technology" },
  { ticker: "INTU",  name: "Intuit Inc.",                   sector: "Information Technology" },
  { ticker: "TXN",   name: "Texas Instruments",             sector: "Information Technology" },
  { ticker: "AMAT",  name: "Applied Materials",             sector: "Information Technology" },
  { ticker: "ADI",   name: "Analog Devices",                sector: "Information Technology" },
  { ticker: "KLAC",  name: "KLA Corp.",                     sector: "Information Technology" },
  { ticker: "LRCX",  name: "Lam Research",                  sector: "Information Technology" },
  { ticker: "MU",    name: "Micron Technology",             sector: "Information Technology" },
  { ticker: "PANW",  name: "Palo Alto Networks",            sector: "Information Technology" },
  { ticker: "CDNS",  name: "Cadence Design Systems",        sector: "Information Technology" },
  { ticker: "SNPS",  name: "Synopsys Inc.",                 sector: "Information Technology" },
  { ticker: "FTNT",  name: "Fortinet Inc.",                 sector: "Information Technology" },
  { ticker: "MCHP",  name: "Microchip Technology",         sector: "Information Technology" },
  { ticker: "GLW",   name: "Corning Inc.",                  sector: "Information Technology" },
  { ticker: "TEL",   name: "TE Connectivity",               sector: "Information Technology" },
  { ticker: "SWKS",  name: "Skyworks Solutions",            sector: "Information Technology" },
  { ticker: "NTAP",  name: "NetApp Inc.",                   sector: "Information Technology" },
  { ticker: "WDC",   name: "Western Digital",               sector: "Information Technology" },
  { ticker: "STX",   name: "Seagate Technology",            sector: "Information Technology" },
  { ticker: "HPQ",   name: "HP Inc.",                       sector: "Information Technology" },
  { ticker: "HPE",   name: "Hewlett Packard Enterprise",    sector: "Information Technology" },
  { ticker: "KEYS",  name: "Keysight Technologies",         sector: "Information Technology" },
  { ticker: "ANSS",  name: "ANSYS Inc.",                    sector: "Information Technology" },
  { ticker: "ZBRA",  name: "Zebra Technologies",            sector: "Information Technology" },
  { ticker: "AKAM",  name: "Akamai Technologies",           sector: "Information Technology" },
  { ticker: "IT",    name: "Gartner Inc.",                  sector: "Information Technology" },
  { ticker: "CDW",   name: "CDW Corp.",                     sector: "Information Technology" },
  { ticker: "ROP",   name: "Roper Technologies",            sector: "Information Technology" },
  { ticker: "TYL",   name: "Tyler Technologies",            sector: "Information Technology" },
  { ticker: "JKHY",  name: "Jack Henry & Associates",       sector: "Information Technology" },
  { ticker: "VRSN",  name: "VeriSign Inc.",                 sector: "Information Technology" },
  { ticker: "CTSH",  name: "Cognizant Technology",          sector: "Information Technology" },
  { ticker: "PTC",   name: "PTC Inc.",                      sector: "Information Technology" },
  { ticker: "TDY",   name: "Teledyne Technologies",         sector: "Information Technology" },
  { ticker: "GDDY",  name: "GoDaddy Inc.",                  sector: "Information Technology" },
  // Notable extras — IT
  { ticker: "SNOW",  name: "Snowflake Inc.",                sector: "Information Technology" },
  { ticker: "CRWD",  name: "CrowdStrike Holdings",          sector: "Information Technology" },
  { ticker: "DDOG",  name: "Datadog Inc.",                  sector: "Information Technology" },
  { ticker: "PLTR",  name: "Palantir Technologies",         sector: "Information Technology" },
  { ticker: "NET",   name: "Cloudflare Inc.",               sector: "Information Technology" },
  { ticker: "ZS",    name: "Zscaler Inc.",                  sector: "Information Technology" },
  { ticker: "OKTA",  name: "Okta Inc.",                     sector: "Information Technology" },
  { ticker: "MDB",   name: "MongoDB Inc.",                  sector: "Information Technology" },
  { ticker: "ZM",    name: "Zoom Video Communications",     sector: "Information Technology" },
  { ticker: "DOCU",  name: "DocuSign Inc.",                 sector: "Information Technology" },
  { ticker: "TWLO",  name: "Twilio Inc.",                   sector: "Information Technology" },
  { ticker: "BILL",  name: "Bill.com Holdings",             sector: "Information Technology" },
  { ticker: "HUBS",  name: "HubSpot Inc.",                  sector: "Information Technology" },
  { ticker: "APP",   name: "Applovin Corp.",                sector: "Information Technology" },

  // ── Communication Services ────────────────────────────────────────────────
  { ticker: "META",  name: "Meta Platforms",                sector: "Communication Services" },
  { ticker: "GOOGL", name: "Alphabet Inc. (Class A)",       sector: "Communication Services" },
  { ticker: "GOOG",  name: "Alphabet Inc. (Class C)",       sector: "Communication Services" },
  { ticker: "NFLX",  name: "Netflix Inc.",                  sector: "Communication Services" },
  { ticker: "DIS",   name: "Walt Disney Co.",               sector: "Communication Services" },
  { ticker: "CMCSA", name: "Comcast Corp.",                 sector: "Communication Services" },
  { ticker: "VZ",    name: "Verizon Communications",        sector: "Communication Services" },
  { ticker: "T",     name: "AT&T Inc.",                     sector: "Communication Services" },
  { ticker: "TMUS",  name: "T-Mobile US",                   sector: "Communication Services" },
  { ticker: "CHTR",  name: "Charter Communications",        sector: "Communication Services" },
  { ticker: "EA",    name: "Electronic Arts",               sector: "Communication Services" },
  { ticker: "TTWO",  name: "Take-Two Interactive",          sector: "Communication Services" },
  { ticker: "WBD",   name: "Warner Bros. Discovery",        sector: "Communication Services" },
  { ticker: "PARA",  name: "Paramount Global",              sector: "Communication Services" },
  { ticker: "FOXA",  name: "Fox Corp.",                     sector: "Communication Services" },
  { ticker: "OMC",   name: "Omnicom Group",                 sector: "Communication Services" },
  { ticker: "IPG",   name: "Interpublic Group",             sector: "Communication Services" },
  { ticker: "MTCH",  name: "Match Group",                   sector: "Communication Services" },
  { ticker: "PINS",  name: "Pinterest Inc.",                sector: "Communication Services" },
  { ticker: "SNAP",  name: "Snap Inc.",                     sector: "Communication Services" },
  { ticker: "RBLX",  name: "Roblox Corp.",                  sector: "Communication Services" },
  { ticker: "SPOT",  name: "Spotify Technology",            sector: "Communication Services" },

  // ── Consumer Discretionary ────────────────────────────────────────────────
  { ticker: "AMZN",  name: "Amazon.com Inc.",               sector: "Consumer Discretionary" },
  { ticker: "TSLA",  name: "Tesla Inc.",                    sector: "Consumer Discretionary" },
  { ticker: "HD",    name: "Home Depot",                    sector: "Consumer Discretionary" },
  { ticker: "MCD",   name: "McDonald's Corp.",              sector: "Consumer Discretionary" },
  { ticker: "NKE",   name: "Nike Inc.",                     sector: "Consumer Discretionary" },
  { ticker: "LOW",   name: "Lowe's Companies",              sector: "Consumer Discretionary" },
  { ticker: "SBUX",  name: "Starbucks Corp.",               sector: "Consumer Discretionary" },
  { ticker: "TJX",   name: "TJX Companies",                 sector: "Consumer Discretionary" },
  { ticker: "BKNG",  name: "Booking Holdings",              sector: "Consumer Discretionary" },
  { ticker: "CMG",   name: "Chipotle Mexican Grill",        sector: "Consumer Discretionary" },
  { ticker: "GM",    name: "General Motors",                sector: "Consumer Discretionary" },
  { ticker: "F",     name: "Ford Motor Co.",                sector: "Consumer Discretionary" },
  { ticker: "ORLY",  name: "O'Reilly Automotive",           sector: "Consumer Discretionary" },
  { ticker: "AZO",   name: "AutoZone Inc.",                 sector: "Consumer Discretionary" },
  { ticker: "EBAY",  name: "eBay Inc.",                     sector: "Consumer Discretionary" },
  { ticker: "ROST",  name: "Ross Stores",                   sector: "Consumer Discretionary" },
  { ticker: "YUM",   name: "Yum! Brands",                   sector: "Consumer Discretionary" },
  { ticker: "DHI",   name: "D.R. Horton",                   sector: "Consumer Discretionary" },
  { ticker: "PHM",   name: "PulteGroup",                    sector: "Consumer Discretionary" },
  { ticker: "LEN",   name: "Lennar Corp.",                  sector: "Consumer Discretionary" },
  { ticker: "NVR",   name: "NVR Inc.",                      sector: "Consumer Discretionary" },
  { ticker: "HLT",   name: "Hilton Worldwide",              sector: "Consumer Discretionary" },
  { ticker: "MAR",   name: "Marriott International",        sector: "Consumer Discretionary" },
  { ticker: "MGM",   name: "MGM Resorts",                   sector: "Consumer Discretionary" },
  { ticker: "WYNN",  name: "Wynn Resorts",                  sector: "Consumer Discretionary" },
  { ticker: "LVS",   name: "Las Vegas Sands",               sector: "Consumer Discretionary" },
  { ticker: "GPC",   name: "Genuine Parts Co.",             sector: "Consumer Discretionary" },
  { ticker: "KMX",   name: "CarMax Inc.",                   sector: "Consumer Discretionary" },
  { ticker: "BBY",   name: "Best Buy Co.",                  sector: "Consumer Discretionary" },
  { ticker: "LULU",  name: "Lululemon Athletica",           sector: "Consumer Discretionary" },
  { ticker: "RL",    name: "Ralph Lauren Corp.",            sector: "Consumer Discretionary" },
  { ticker: "PVH",   name: "PVH Corp.",                     sector: "Consumer Discretionary" },
  { ticker: "TPR",   name: "Tapestry Inc.",                 sector: "Consumer Discretionary" },
  { ticker: "ETSY",  name: "Etsy Inc.",                     sector: "Consumer Discretionary" },
  { ticker: "RCL",   name: "Royal Caribbean",               sector: "Consumer Discretionary" },
  { ticker: "CCL",   name: "Carnival Corp.",                sector: "Consumer Discretionary" },
  { ticker: "NCLH",  name: "Norwegian Cruise Line",         sector: "Consumer Discretionary" },
  { ticker: "APTV",  name: "Aptiv PLC",                     sector: "Consumer Discretionary" },
  { ticker: "BWA",   name: "BorgWarner Inc.",               sector: "Consumer Discretionary" },
  { ticker: "POOL",  name: "Pool Corp.",                    sector: "Consumer Discretionary" },
  { ticker: "DG",    name: "Dollar General",                sector: "Consumer Discretionary" },
  { ticker: "DLTR",  name: "Dollar Tree",                   sector: "Consumer Discretionary" },
  { ticker: "EXPE",  name: "Expedia Group",                 sector: "Consumer Discretionary" },
  // Notable extras — Consumer Discretionary
  { ticker: "ABNB",  name: "Airbnb Inc.",                   sector: "Consumer Discretionary" },
  { ticker: "DASH",  name: "DoorDash Inc.",                 sector: "Consumer Discretionary" },
  { ticker: "DKNG",  name: "DraftKings Inc.",               sector: "Consumer Discretionary" },
  { ticker: "RIVN",  name: "Rivian Automotive",             sector: "Consumer Discretionary" },

  // ── Consumer Staples ──────────────────────────────────────────────────────
  { ticker: "PG",    name: "Procter & Gamble",              sector: "Consumer Staples" },
  { ticker: "KO",    name: "Coca-Cola Co.",                 sector: "Consumer Staples" },
  { ticker: "PEP",   name: "PepsiCo Inc.",                  sector: "Consumer Staples" },
  { ticker: "COST",  name: "Costco Wholesale",              sector: "Consumer Staples" },
  { ticker: "WMT",   name: "Walmart Inc.",                  sector: "Consumer Staples" },
  { ticker: "TGT",   name: "Target Corp.",                  sector: "Consumer Staples" },
  { ticker: "PM",    name: "Philip Morris International",   sector: "Consumer Staples" },
  { ticker: "MO",    name: "Altria Group",                  sector: "Consumer Staples" },
  { ticker: "MDLZ",  name: "Mondelez International",        sector: "Consumer Staples" },
  { ticker: "CL",    name: "Colgate-Palmolive",             sector: "Consumer Staples" },
  { ticker: "KMB",   name: "Kimberly-Clark",                sector: "Consumer Staples" },
  { ticker: "GIS",   name: "General Mills",                 sector: "Consumer Staples" },
  { ticker: "K",     name: "Kellanova",                     sector: "Consumer Staples" },
  { ticker: "SJM",   name: "J.M. Smucker",                 sector: "Consumer Staples" },
  { ticker: "CPB",   name: "Campbell Soup",                 sector: "Consumer Staples" },
  { ticker: "HSY",   name: "Hershey Co.",                   sector: "Consumer Staples" },
  { ticker: "MKC",   name: "McCormick & Co.",               sector: "Consumer Staples" },
  { ticker: "CAG",   name: "ConAgra Brands",                sector: "Consumer Staples" },
  { ticker: "HRL",   name: "Hormel Foods",                  sector: "Consumer Staples" },
  { ticker: "KHC",   name: "Kraft Heinz",                   sector: "Consumer Staples" },
  { ticker: "SYY",   name: "Sysco Corp.",                   sector: "Consumer Staples" },
  { ticker: "ADM",   name: "Archer-Daniels-Midland",        sector: "Consumer Staples" },
  { ticker: "STZ",   name: "Constellation Brands",          sector: "Consumer Staples" },
  { ticker: "MNST",  name: "Monster Beverage",              sector: "Consumer Staples" },
  { ticker: "KDP",   name: "Keurig Dr Pepper",              sector: "Consumer Staples" },
  { ticker: "EL",    name: "Estee Lauder",                  sector: "Consumer Staples" },
  { ticker: "CHD",   name: "Church & Dwight",               sector: "Consumer Staples" },

  // ── Energy ────────────────────────────────────────────────────────────────
  { ticker: "XOM",   name: "Exxon Mobil",                   sector: "Energy" },
  { ticker: "CVX",   name: "Chevron Corp.",                 sector: "Energy" },
  { ticker: "COP",   name: "ConocoPhillips",                sector: "Energy" },
  { ticker: "SLB",   name: "Schlumberger (SLB)",            sector: "Energy" },
  { ticker: "EOG",   name: "EOG Resources",                 sector: "Energy" },
  { ticker: "PSX",   name: "Phillips 66",                   sector: "Energy" },
  { ticker: "VLO",   name: "Valero Energy",                 sector: "Energy" },
  { ticker: "MPC",   name: "Marathon Petroleum",            sector: "Energy" },
  { ticker: "HES",   name: "Hess Corp.",                    sector: "Energy" },
  { ticker: "CTRA",  name: "Coterra Energy",                sector: "Energy" },
  { ticker: "DVN",   name: "Devon Energy",                  sector: "Energy" },
  { ticker: "FANG",  name: "Diamondback Energy",            sector: "Energy" },
  { ticker: "OXY",   name: "Occidental Petroleum",          sector: "Energy" },
  { ticker: "BKR",   name: "Baker Hughes",                  sector: "Energy" },
  { ticker: "HAL",   name: "Halliburton",                   sector: "Energy" },
  { ticker: "APA",   name: "APA Corp.",                     sector: "Energy" },
  { ticker: "TRGP",  name: "Targa Resources",               sector: "Energy" },
  { ticker: "KMI",   name: "Kinder Morgan",                 sector: "Energy" },
  { ticker: "WMB",   name: "Williams Companies",            sector: "Energy" },
  { ticker: "OKE",   name: "ONEOK Inc.",                    sector: "Energy" },

  // ── Financials ────────────────────────────────────────────────────────────
  { ticker: "JPM",   name: "JPMorgan Chase",                sector: "Financials" },
  { ticker: "BAC",   name: "Bank of America",               sector: "Financials" },
  { ticker: "WFC",   name: "Wells Fargo",                   sector: "Financials" },
  { ticker: "GS",    name: "Goldman Sachs",                 sector: "Financials" },
  { ticker: "MS",    name: "Morgan Stanley",                sector: "Financials" },
  { ticker: "C",     name: "Citigroup",                     sector: "Financials" },
  { ticker: "AXP",   name: "American Express",              sector: "Financials" },
  { ticker: "BLK",   name: "BlackRock Inc.",                sector: "Financials" },
  { ticker: "SPGI",  name: "S&P Global",                    sector: "Financials" },
  { ticker: "MCO",   name: "Moody's Corp.",                 sector: "Financials" },
  { ticker: "ICE",   name: "Intercontinental Exchange",     sector: "Financials" },
  { ticker: "CME",   name: "CME Group",                     sector: "Financials" },
  { ticker: "SCHW",  name: "Charles Schwab",                sector: "Financials" },
  { ticker: "CB",    name: "Chubb Ltd.",                    sector: "Financials" },
  { ticker: "MMC",   name: "Marsh & McLennan",              sector: "Financials" },
  { ticker: "AON",   name: "Aon plc",                       sector: "Financials" },
  { ticker: "MET",   name: "MetLife Inc.",                  sector: "Financials" },
  { ticker: "PRU",   name: "Prudential Financial",          sector: "Financials" },
  { ticker: "ALL",   name: "Allstate Corp.",                sector: "Financials" },
  { ticker: "AIG",   name: "American International Group",  sector: "Financials" },
  { ticker: "TRV",   name: "Travelers Companies",           sector: "Financials" },
  { ticker: "AFL",   name: "Aflac Inc.",                    sector: "Financials" },
  { ticker: "HIG",   name: "Hartford Financial",            sector: "Financials" },
  { ticker: "USB",   name: "U.S. Bancorp",                  sector: "Financials" },
  { ticker: "PNC",   name: "PNC Financial",                 sector: "Financials" },
  { ticker: "TFC",   name: "Truist Financial",              sector: "Financials" },
  { ticker: "COF",   name: "Capital One Financial",         sector: "Financials" },
  { ticker: "DFS",   name: "Discover Financial",            sector: "Financials" },
  { ticker: "SYF",   name: "Synchrony Financial",           sector: "Financials" },
  { ticker: "AMP",   name: "Ameriprise Financial",          sector: "Financials" },
  { ticker: "RJF",   name: "Raymond James Financial",       sector: "Financials" },
  { ticker: "BK",    name: "Bank of New York Mellon",       sector: "Financials" },
  { ticker: "STT",   name: "State Street Corp.",            sector: "Financials" },
  { ticker: "TROW",  name: "T. Rowe Price",                 sector: "Financials" },
  { ticker: "KEY",   name: "KeyCorp",                       sector: "Financials" },
  { ticker: "RF",    name: "Regions Financial",             sector: "Financials" },
  { ticker: "FITB",  name: "Fifth Third Bancorp",           sector: "Financials" },
  { ticker: "CFG",   name: "Citizens Financial",            sector: "Financials" },
  { ticker: "HBAN",  name: "Huntington Bancshares",         sector: "Financials" },
  { ticker: "BRK-B", name: "Berkshire Hathaway",            sector: "Financials" },
  // Notable extras — Financials
  { ticker: "COIN",  name: "Coinbase Global",               sector: "Financials" },
  { ticker: "HOOD",  name: "Robinhood Markets",             sector: "Financials" },
  { ticker: "SOFI",  name: "SoFi Technologies",             sector: "Financials" },
  { ticker: "AFRM",  name: "Affirm Holdings",               sector: "Financials" },

  // ── Health Care ───────────────────────────────────────────────────────────
  { ticker: "LLY",   name: "Eli Lilly",                     sector: "Health Care" },
  { ticker: "UNH",   name: "UnitedHealth Group",            sector: "Health Care" },
  { ticker: "JNJ",   name: "Johnson & Johnson",             sector: "Health Care" },
  { ticker: "ABBV",  name: "AbbVie Inc.",                   sector: "Health Care" },
  { ticker: "MRK",   name: "Merck & Co.",                   sector: "Health Care" },
  { ticker: "TMO",   name: "Thermo Fisher Scientific",      sector: "Health Care" },
  { ticker: "ABT",   name: "Abbott Laboratories",           sector: "Health Care" },
  { ticker: "DHR",   name: "Danaher Corp.",                 sector: "Health Care" },
  { ticker: "BMY",   name: "Bristol-Myers Squibb",          sector: "Health Care" },
  { ticker: "PFE",   name: "Pfizer Inc.",                   sector: "Health Care" },
  { ticker: "AMGN",  name: "Amgen Inc.",                    sector: "Health Care" },
  { ticker: "MDT",   name: "Medtronic plc",                 sector: "Health Care" },
  { ticker: "BSX",   name: "Boston Scientific",             sector: "Health Care" },
  { ticker: "SYK",   name: "Stryker Corp.",                 sector: "Health Care" },
  { ticker: "ISRG",  name: "Intuitive Surgical",            sector: "Health Care" },
  { ticker: "CVS",   name: "CVS Health",                    sector: "Health Care" },
  { ticker: "CI",    name: "Cigna Group",                   sector: "Health Care" },
  { ticker: "ELV",   name: "Elevance Health",               sector: "Health Care" },
  { ticker: "HUM",   name: "Humana Inc.",                   sector: "Health Care" },
  { ticker: "CNC",   name: "Centene Corp.",                 sector: "Health Care" },
  { ticker: "MCK",   name: "McKesson Corp.",                sector: "Health Care" },
  { ticker: "CAH",   name: "Cardinal Health",               sector: "Health Care" },
  { ticker: "VRTX",  name: "Vertex Pharmaceuticals",        sector: "Health Care" },
  { ticker: "REGN",  name: "Regeneron Pharmaceuticals",     sector: "Health Care" },
  { ticker: "GILD",  name: "Gilead Sciences",               sector: "Health Care" },
  { ticker: "BIIB",  name: "Biogen Inc.",                   sector: "Health Care" },
  { ticker: "GEHC",  name: "GE HealthCare",                 sector: "Health Care" },
  { ticker: "IQV",   name: "IQVIA Holdings",                sector: "Health Care" },
  { ticker: "IDXX",  name: "IDEXX Laboratories",            sector: "Health Care" },
  { ticker: "A",     name: "Agilent Technologies",          sector: "Health Care" },
  { ticker: "BAX",   name: "Baxter International",          sector: "Health Care" },
  { ticker: "BDX",   name: "Becton Dickinson",              sector: "Health Care" },
  { ticker: "DXCM",  name: "Dexcom Inc.",                   sector: "Health Care" },
  { ticker: "MOH",   name: "Molina Healthcare",             sector: "Health Care" },
  { ticker: "EW",    name: "Edwards Lifesciences",          sector: "Health Care" },
  { ticker: "WAT",   name: "Waters Corp.",                  sector: "Health Care" },
  { ticker: "MTD",   name: "Mettler-Toledo",                sector: "Health Care" },
  { ticker: "ZBH",   name: "Zimmer Biomet",                 sector: "Health Care" },
  { ticker: "RMD",   name: "ResMed Inc.",                   sector: "Health Care" },
  { ticker: "PODD",  name: "Insulet Corp.",                 sector: "Health Care" },
  { ticker: "CRL",   name: "Charles River Laboratories",    sector: "Health Care" },
  { ticker: "HOLX",  name: "Hologic Inc.",                  sector: "Health Care" },
  { ticker: "ALGN",  name: "Align Technology",              sector: "Health Care" },
  { ticker: "STE",   name: "STERIS plc",                    sector: "Health Care" },
  { ticker: "VTRS",  name: "Viatris Inc.",                  sector: "Health Care" },
  { ticker: "OGN",   name: "Organon & Co.",                 sector: "Health Care" },
  { ticker: "MRNA",  name: "Moderna Inc.",                  sector: "Health Care" },
  { ticker: "ILMN",  name: "Illumina Inc.",                 sector: "Health Care" },

  // ── Industrials ───────────────────────────────────────────────────────────
  { ticker: "GE",    name: "GE Aerospace",                  sector: "Industrials" },
  { ticker: "HON",   name: "Honeywell International",       sector: "Industrials" },
  { ticker: "UPS",   name: "United Parcel Service",         sector: "Industrials" },
  { ticker: "CAT",   name: "Caterpillar Inc.",              sector: "Industrials" },
  { ticker: "BA",    name: "Boeing Co.",                    sector: "Industrials" },
  { ticker: "RTX",   name: "RTX Corp.",                     sector: "Industrials" },
  { ticker: "DE",    name: "Deere & Co.",                   sector: "Industrials" },
  { ticker: "LMT",   name: "Lockheed Martin",               sector: "Industrials" },
  { ticker: "NOC",   name: "Northrop Grumman",              sector: "Industrials" },
  { ticker: "GD",    name: "General Dynamics",              sector: "Industrials" },
  { ticker: "FDX",   name: "FedEx Corp.",                   sector: "Industrials" },
  { ticker: "UNP",   name: "Union Pacific",                 sector: "Industrials" },
  { ticker: "CSX",   name: "CSX Corp.",                     sector: "Industrials" },
  { ticker: "NSC",   name: "Norfolk Southern",              sector: "Industrials" },
  { ticker: "WM",    name: "Waste Management",              sector: "Industrials" },
  { ticker: "RSG",   name: "Republic Services",             sector: "Industrials" },
  { ticker: "ROK",   name: "Rockwell Automation",           sector: "Industrials" },
  { ticker: "EMR",   name: "Emerson Electric",              sector: "Industrials" },
  { ticker: "ETN",   name: "Eaton Corp.",                   sector: "Industrials" },
  { ticker: "PH",    name: "Parker Hannifin",               sector: "Industrials" },
  { ticker: "ITW",   name: "Illinois Tool Works",           sector: "Industrials" },
  { ticker: "GWW",   name: "W.W. Grainger",                 sector: "Industrials" },
  { ticker: "MMM",   name: "3M Co.",                        sector: "Industrials" },
  { ticker: "IR",    name: "Ingersoll Rand",                sector: "Industrials" },
  { ticker: "SWK",   name: "Stanley Black & Decker",        sector: "Industrials" },
  { ticker: "DOV",   name: "Dover Corp.",                   sector: "Industrials" },
  { ticker: "XYL",   name: "Xylem Inc.",                    sector: "Industrials" },
  { ticker: "PCAR",  name: "PACCAR Inc.",                   sector: "Industrials" },
  { ticker: "CMI",   name: "Cummins Inc.",                  sector: "Industrials" },
  { ticker: "CTAS",  name: "Cintas Corp.",                  sector: "Industrials" },
  { ticker: "FAST",  name: "Fastenal Co.",                  sector: "Industrials" },
  { ticker: "AME",   name: "AMETEK Inc.",                   sector: "Industrials" },
  { ticker: "OTIS",  name: "Otis Worldwide",                sector: "Industrials" },
  { ticker: "CARR",  name: "Carrier Global",                sector: "Industrials" },
  { ticker: "TT",    name: "Trane Technologies",            sector: "Industrials" },
  { ticker: "JCI",   name: "Johnson Controls",              sector: "Industrials" },
  { ticker: "AXON",  name: "Axon Enterprise",               sector: "Industrials" },
  { ticker: "CHRW",  name: "C.H. Robinson",                 sector: "Industrials" },
  { ticker: "EXPD",  name: "Expeditors International",      sector: "Industrials" },
  { ticker: "JBHT",  name: "J.B. Hunt Transport",           sector: "Industrials" },
  { ticker: "LUV",   name: "Southwest Airlines",            sector: "Industrials" },
  { ticker: "DAL",   name: "Delta Air Lines",               sector: "Industrials" },
  { ticker: "UAL",   name: "United Airlines",               sector: "Industrials" },
  { ticker: "AAL",   name: "American Airlines",             sector: "Industrials" },
  { ticker: "ALK",   name: "Alaska Air Group",              sector: "Industrials" },
  { ticker: "HEI",   name: "HEICO Corp.",                   sector: "Industrials" },
  { ticker: "TDG",   name: "TransDigm Group",               sector: "Industrials" },
  { ticker: "GGG",   name: "Graco Inc.",                    sector: "Industrials" },
  { ticker: "MSA",   name: "MSA Safety",                    sector: "Industrials" },
  // Notable extras — Industrials
  { ticker: "UBER",  name: "Uber Technologies",             sector: "Industrials" },
  { ticker: "LYFT",  name: "Lyft Inc.",                     sector: "Industrials" },

  // ── Materials ─────────────────────────────────────────────────────────────
  { ticker: "LIN",   name: "Linde plc",                     sector: "Materials" },
  { ticker: "APD",   name: "Air Products & Chemicals",      sector: "Materials" },
  { ticker: "SHW",   name: "Sherwin-Williams",              sector: "Materials" },
  { ticker: "ECL",   name: "Ecolab Inc.",                   sector: "Materials" },
  { ticker: "PPG",   name: "PPG Industries",                sector: "Materials" },
  { ticker: "NEM",   name: "Newmont Corp.",                 sector: "Materials" },
  { ticker: "FCX",   name: "Freeport-McMoRan",              sector: "Materials" },
  { ticker: "NUE",   name: "Nucor Corp.",                   sector: "Materials" },
  { ticker: "STLD",  name: "Steel Dynamics",                sector: "Materials" },
  { ticker: "ALB",   name: "Albemarle Corp.",               sector: "Materials" },
  { ticker: "CF",    name: "CF Industries",                 sector: "Materials" },
  { ticker: "MOS",   name: "Mosaic Co.",                    sector: "Materials" },
  { ticker: "VMC",   name: "Vulcan Materials",              sector: "Materials" },
  { ticker: "MLM",   name: "Martin Marietta Materials",     sector: "Materials" },
  { ticker: "PKG",   name: "Packaging Corp. of America",    sector: "Materials" },
  { ticker: "IFF",   name: "International Flavors",         sector: "Materials" },
  { ticker: "CE",    name: "Celanese Corp.",                sector: "Materials" },
  { ticker: "DD",    name: "DuPont de Nemours",             sector: "Materials" },
  { ticker: "EMN",   name: "Eastman Chemical",              sector: "Materials" },
  { ticker: "RPM",   name: "RPM International",             sector: "Materials" },

  // ── Real Estate ───────────────────────────────────────────────────────────
  { ticker: "AMT",   name: "American Tower",                sector: "Real Estate" },
  { ticker: "PLD",   name: "Prologis Inc.",                 sector: "Real Estate" },
  { ticker: "EQIX",  name: "Equinix Inc.",                  sector: "Real Estate" },
  { ticker: "CCI",   name: "Crown Castle",                  sector: "Real Estate" },
  { ticker: "PSA",   name: "Public Storage",                sector: "Real Estate" },
  { ticker: "DLR",   name: "Digital Realty Trust",          sector: "Real Estate" },
  { ticker: "O",     name: "Realty Income",                 sector: "Real Estate" },
  { ticker: "VICI",  name: "VICI Properties",               sector: "Real Estate" },
  { ticker: "WELL",  name: "Welltower Inc.",                sector: "Real Estate" },
  { ticker: "SPG",   name: "Simon Property Group",          sector: "Real Estate" },
  { ticker: "VTR",   name: "Ventas Inc.",                   sector: "Real Estate" },
  { ticker: "ARE",   name: "Alexandria Real Estate",        sector: "Real Estate" },
  { ticker: "EQR",   name: "Equity Residential",            sector: "Real Estate" },
  { ticker: "AVB",   name: "AvalonBay Communities",         sector: "Real Estate" },
  { ticker: "CPT",   name: "Camden Property Trust",         sector: "Real Estate" },
  { ticker: "NNN",   name: "NNN REIT",                      sector: "Real Estate" },
  { ticker: "CBRE",  name: "CBRE Group",                    sector: "Real Estate" },
  { ticker: "CSGP",  name: "CoStar Group",                  sector: "Real Estate" },

  // ── Utilities ─────────────────────────────────────────────────────────────
  { ticker: "NEE",   name: "NextEra Energy",                sector: "Utilities" },
  { ticker: "DUK",   name: "Duke Energy",                   sector: "Utilities" },
  { ticker: "SO",    name: "Southern Co.",                  sector: "Utilities" },
  { ticker: "D",     name: "Dominion Energy",               sector: "Utilities" },
  { ticker: "AEP",   name: "American Electric Power",       sector: "Utilities" },
  { ticker: "EXC",   name: "Exelon Corp.",                  sector: "Utilities" },
  { ticker: "XEL",   name: "Xcel Energy",                   sector: "Utilities" },
  { ticker: "SRE",   name: "Sempra Energy",                 sector: "Utilities" },
  { ticker: "ED",    name: "Consolidated Edison",           sector: "Utilities" },
  { ticker: "WEC",   name: "WEC Energy Group",              sector: "Utilities" },
  { ticker: "DTE",   name: "DTE Energy",                    sector: "Utilities" },
  { ticker: "AWK",   name: "American Water Works",          sector: "Utilities" },
  { ticker: "ES",    name: "Eversource Energy",             sector: "Utilities" },
  { ticker: "AEE",   name: "Ameren Corp.",                  sector: "Utilities" },
  { ticker: "CNP",   name: "CenterPoint Energy",            sector: "Utilities" },
  { ticker: "PEG",   name: "Public Service Enterprise",     sector: "Utilities" },
  { ticker: "PCG",   name: "PG&E Corp.",                    sector: "Utilities" },
  { ticker: "FE",    name: "FirstEnergy Corp.",             sector: "Utilities" },
  { ticker: "ETR",   name: "Entergy Corp.",                 sector: "Utilities" },
  { ticker: "PPL",   name: "PPL Corp.",                     sector: "Utilities" },
  { ticker: "LNT",   name: "Alliant Energy",                sector: "Utilities" },
  { ticker: "EVRG",  name: "Evergy Inc.",                   sector: "Utilities" },
  { ticker: "NI",    name: "NiSource Inc.",                 sector: "Utilities" },
];

export const SECTOR_LIST = Array.from(
  new Set(STOCK_UNIVERSE.map((s) => s.sector))
).sort();

export const UNIVERSE_MAP = new Map(
  STOCK_UNIVERSE.map((s) => [s.ticker, s])
);
